#!/bin/bash
# Claude Code status line — Dracula theme
# Generated by webup-statusline skill

# Ensure jq is available (Windows: WinGet/scoop installs may not be on PATH)
if ! command -v jq >/dev/null 2>&1; then
  for _jq_dir in \
    "/c/Users/$USERNAME/AppData/Local/Microsoft/WinGet/Links" \
    "/c/Users/$USERNAME/AppData/Local/Microsoft/WinGet/Packages/jqlang.jq_Microsoft.Winget.Source_8wekyb3d8bbwe" \
    "$HOME/scoop/shims" \
  ; do
    if [ -d "$_jq_dir" ] && { [ -x "$_jq_dir/jq" ] || [ -x "$_jq_dir/jq.exe" ]; }; then
      export PATH="$PATH:$_jq_dir"
      break
    fi
  done
  if ! command -v jq >/dev/null 2>&1; then
    echo "claude-status: jq is required but not installed." >&2
    echo "  Install via: winget install jqlang.jq  OR  scoop install jq" >&2
    exit 1
  fi
fi
# Colors
readonly RST='\033[0m'
readonly C_MODEL='\033[38;2;189;147;249m'
readonly C_CTX_OK='\033[38;2;80;250;123m'
readonly C_CTX_WARN='\033[38;2;241;250;140m'
readonly C_CTX_LOW='\033[38;2;255;85;85m'
readonly C_BAR_EMPTY='\033[38;2;68;71;90m'
readonly C_PCT='\033[38;2;248;248;242m'
readonly C_DIR='\033[38;2;139;233;253m'
readonly C_GIT='\033[38;2;255;184;108m'
readonly C_GIT_DIRTY='\033[38;2;241;250;140m'
readonly C_VIM='\033[38;2;241;250;140m'
readonly C_WORKTREE='\033[38;2;255;121;198m'
readonly C_STYLE='\033[38;2;189;147;249m'
readonly C_COST='\033[38;2;255;215;0m'
readonly C_QUOTA='\033[38;2;255;121;198m'
readonly C_RESET_IN='\033[2;38;2;98;114;164m'
readonly C_EFFORT_HIGH='\033[1;38;2;255;85;85m'
readonly C_EFFORT_MED='\033[38;2;241;250;140m'
readonly C_EFFORT_LOW='\033[38;2;80;250;123m'
readonly C_EFFORT_OFF='\033[2;38;2;98;114;164m'
readonly C_CACHE_HOT='\033[38;2;255;85;85m'
readonly C_CACHE_COLD='\033[38;2;110;170;240m'
readonly C_SEP='\033[38;2;98;114;164m'

readonly SEP=" | "

# Read JSON from stdin
input=$(cat)

model=$(echo "$input" | jq -r '.model.display_name // ""')
remaining=$(echo "$input" | jq -r 'if .context_window.remaining_percentage != null then (.context_window.remaining_percentage | floor) else "" end')
ctx_used_tokens=$(echo "$input" | jq -r '.context_window.total_input_tokens // empty')
ctx_window_size=$(echo "$input" | jq -r '.context_window.context_window_size // empty')
# Prompt-cache stats (absent until the main conversation's first API response)
cache_hit_ratio=$(echo "$input" | jq -r 'if .prompt_cache.hit_ratio != null then (.prompt_cache.hit_ratio | tostring) else "" end')
cache_warm=$(echo "$input" | jq -r '.prompt_cache.warm // empty')
# Reasoning effort: prefer the live value from stdin; fall back to the
# settings-file mechanism that older versions used
effort=$(echo "$input" | jq -r '.effort.level // empty')
if [ -z "$effort" ]; then
  for f in "$HOME/.claude/settings.local.json" "$HOME/.claude/.claude/settings.local.json" "$HOME/.claude/settings.json"; do
    if [ -z "$effort" ] && [ -f "$f" ]; then
      effort=$(jq -r '.effortLevel // empty' "$f" 2>/dev/null)
    fi
  done
fi
thinking_enabled=$(echo "$input" | jq -r '.thinking.enabled // empty')
current_dir=$(echo "$input" | jq -r '.workspace.current_dir // ""')
original_repo_dir=$(echo "$input" | jq -r '.worktree.original_repo_dir // empty')
output_style=$(echo "$input" | jq -r '.output_style.name // empty')
cost_usd=$(echo "$input" | jq -r '.cost.total_cost_usd // empty')
worktree_name=$(echo "$input" | jq -r '.worktree.name // empty')
worktree_branch=$(echo "$input" | jq -r '.worktree.branch // empty')
# Claude.ai subscription rate limits (Pro/Max only, absent until the first API
# response in a session; each window may be independently missing)
rl_5h=$(echo "$input" | jq -r 'if .rate_limits.five_hour.used_percentage != null then (.rate_limits.five_hour.used_percentage | floor) else "" end')
rl_7d=$(echo "$input" | jq -r 'if .rate_limits.seven_day.used_percentage != null then (.rate_limits.seven_day.used_percentage | floor) else "" end')
rl_5h_at=$(echo "$input" | jq -r '.rate_limits.five_hour.resets_at // empty')
rl_7d_at=$(echo "$input" | jq -r '.rate_limits.seven_day.resets_at // empty')

# Worktree detection (git fallback for external worktrees)
is_worktree=0
if [ -n "$worktree_name" ]; then
  is_worktree=1
elif [ -n "$current_dir" ] && git -C "$current_dir" --no-optional-locks rev-parse --git-dir > /dev/null 2>&1; then
  _gd=$(git -C "$current_dir" --no-optional-locks rev-parse --git-dir 2>/dev/null)
  _gcd=$(git -C "$current_dir" --no-optional-locks rev-parse --git-common-dir 2>/dev/null)
  if [ -n "$_gd" ] && [ -n "$_gcd" ] && [ "$_gd" != "$_gcd" ]; then
    is_worktree=1
    if [ -z "$worktree_name" ]; then
      # Use parent dir basename as worktree id (e.g. ~/.codex/worktrees/46a6/clawmaster -> 46a6)
      _parent=$(dirname "$current_dir")
      worktree_name=$(basename "$_parent")
      # Fall back to current dir basename if parent is a generic bucket
      case "$worktree_name" in
        worktrees|wt|.codex|.claude) worktree_name=$(basename "$current_dir") ;;
      esac
    fi
  fi
fi

# Git branch (prefer worktree.branch from input, fall back to git CLI)
git_branch="$worktree_branch"
git_dirty=0
if [ -n "$current_dir" ] && git -C "$current_dir" --no-optional-locks rev-parse --git-dir > /dev/null 2>&1; then
  if [ -z "$git_branch" ]; then
    git_branch=$(git -C "$current_dir" --no-optional-locks branch --show-current 2>/dev/null)
  fi
  if [ -n "$git_branch" ]; then
    if ! git -C "$current_dir" --no-optional-locks diff --quiet 2>/dev/null || \
       ! git -C "$current_dir" --no-optional-locks diff --cached --quiet 2>/dev/null; then
      git_dirty=1
    fi
  fi
fi

# Shorten directory (prefer original repo when in a worktree)
short_dir=""
if [ -n "$original_repo_dir" ]; then
  short_dir=$(basename "$original_repo_dir")
elif [ -n "$current_dir" ]; then
  short_dir=$(basename "$current_dir")
fi

# Progress bar (color scales with remaining context)
bar=""
if [ -n "$remaining" ]; then
  used=$((100 - remaining))
  filled=$((used / 5))
  empty=$((20 - filled))
  if [ "$remaining" -lt 20 ]; then
    ctx_color="$C_CTX_LOW"
  elif [ "$remaining" -lt 50 ]; then
    ctx_color="$C_CTX_WARN"
  else
    ctx_color="$C_CTX_OK"
  fi
  bar="${C_SEP}[${RST}"
  for ((i=0; i<filled; i++)); do bar+="${ctx_color}■${RST}"; done
  for ((i=0; i<empty; i++)); do bar+="${C_BAR_EMPTY}□${RST}"; done
  bar+="${C_SEP}]${RST} ${ctx_color}${used}%${RST}"
  # Append token counts when available: used_tokens/window_size
  if [ -n "$ctx_used_tokens" ] && [ -n "$ctx_window_size" ]; then
    ctx_used_k=$(awk -v v="$ctx_used_tokens" 'BEGIN { printf "%.0fk", v/1000 }')
    ctx_total_k=$(awk -v v="$ctx_window_size" 'BEGIN { printf "%.0fk", v/1000 }')
    bar+="${C_SEP} (${RST}${ctx_color}${ctx_used_k}${RST}${C_SEP}/${RST}${ctx_color}${ctx_total_k}${RST}${C_SEP})${RST}"
  fi
fi

# Rate-limit quota (colors are inverted vs the context bar: this is percent USED,
# so a high number is the bad case)
rl_color() {
  if [ "$1" -ge 80 ]; then printf '%b' "$C_CTX_LOW"
  elif [ "$1" -ge 50 ]; then printf '%b' "$C_CTX_WARN"
  else printf '%b' "$C_CTX_OK"
  fi
}
# Time remaining until a quota window resets, as a compact countdown (e.g. 2h13m, 3d5h)
rl_reset_in() {
  local at="$1" now delta d h m
  case "$at" in ''|*[!0-9]*) return ;; esac   # absent or non-numeric
  now=$(date +%s)
  delta=$(( at - now ))
  [ "$delta" -le 0 ] && { printf 'now'; return; }
  d=$(( delta / 86400 ))
  h=$(( (delta % 86400) / 3600 ))
  m=$(( (delta % 3600) / 60 ))
  if   [ "$d" -gt 0 ]; then printf '%dd%dh' "$d" "$h"
  elif [ "$h" -gt 0 ]; then printf '%dh%dm' "$h" "$m"
  else                      printf '%dm' "$m"
  fi
}
quota=""
if [ -n "$rl_5h" ] || [ -n "$rl_7d" ]; then
  quota="${C_QUOTA}◷${RST}"
  if [ -n "$rl_5h" ]; then
    quota+=" ${C_SEP}5h${RST} $(rl_color "$rl_5h")${rl_5h}%${RST}"
    _in=$(rl_reset_in "$rl_5h_at")
    [ -n "$_in" ] && quota+="${C_RESET_IN} ↻${_in}${RST}"
  fi
  if [ -n "$rl_7d" ]; then
    [ -n "$rl_5h" ] && quota+="${C_SEP} ·${RST}"
    quota+=" ${C_SEP}7d${RST} $(rl_color "$rl_7d")${rl_7d}%${RST}"
    _in=$(rl_reset_in "$rl_7d_at")
    [ -n "$_in" ] && quota+="${C_RESET_IN} ↻${_in}${RST}"
  fi
fi

# Prompt-cache hit ratio. The percentage color marks cache state
# (red = warm/hot, blue = cold); ⚡ stays uncolored because terminals
# render it as a colored emoji
cache=""
if [ -n "$cache_hit_ratio" ]; then
  cache_pct=$(awk -v r="$cache_hit_ratio" 'BEGIN { printf "%.0f%%", r*100 }')
  if   [ "$cache_warm" = "true" ]; then pct_color="$C_CACHE_HOT"
  else pct_color="$C_CACHE_COLD"
  fi
  cache="⚡ ${pct_color}${cache_pct}${RST}"
else
  cache="⚡${C_RESET_IN} —${RST}"
fi

# Assemble
parts=()

if [ -n "$model" ]; then
  parts+=("${C_MODEL}◈ ${model}${RST}")
fi

if [ -n "$bar" ]; then
  parts+=("${bar}")
fi

if [ -n "$cache" ]; then
  parts+=("${cache}")
fi

if [ -n "$quota" ]; then
  parts+=("${quota}")
fi

if [ -n "$cost_usd" ]; then
  cost_formatted=$(awk -v v="$cost_usd" 'BEGIN { if (v+0 >= 0.005) printf "$%.2f", v+0 }')
  if [ -n "$cost_formatted" ]; then
    parts+=("${C_COST}${cost_formatted}${RST}")
  fi
fi

# Color effort by level (max/xhigh/high share the bold-red pressure tier)
if [ -n "$effort" ]; then
  case "$effort" in
    max|MAX|Max|xhigh|XHIGH|XHigh|high|High|HIGH)  effort_color="$C_EFFORT_HIGH" ;;
    medium|Medium|MEDIUM)                          effort_color="$C_EFFORT_MED" ;;
    low|Low|LOW|xlow|XLow|XLOW|minimal|Minimal)    effort_color="$C_EFFORT_LOW" ;;
    *)                                             effort_color="$C_EFFORT_OFF" ;;
  esac
  parts+=("${effort_color}↯ ${effort}${RST}")
elif [ "$thinking_enabled" = "true" ]; then
  parts+=("${C_EFFORT_OFF}↯ thinking${RST}")
fi

if [ -n "$output_style" ] && [ "$output_style" != "default" ]; then
  parts+=("${C_STYLE}❋ ${output_style}${RST}")
fi

if [ -n "$short_dir" ]; then
  parts+=("${C_DIR}目录: ${short_dir}${RST}")
fi

if [ "$is_worktree" -eq 1 ] && [ -n "$worktree_name" ]; then
  parts+=("\033[1m${C_WORKTREE}⊕ worktree:${worktree_name}${RST}")
fi

if [ -n "$git_branch" ]; then
  if [ "$git_dirty" -eq 1 ]; then
    parts+=("${C_GIT_DIRTY}⎇ ${git_branch}${RST}")
  else
    parts+=("${C_GIT}⎇ ${git_branch}${RST}")
  fi
fi

# Output
output=""
for i in "${!parts[@]}"; do
  if [ "$i" -gt 0 ]; then
    output+="${C_SEP}${SEP}${RST}"
  fi
  output+="${parts[$i]}"
done

printf "%b" "$output"
